[project]
name = "lbm-poiseuille"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pandas>=2.0.0",
    "jinja2>=3.1.0",
]
